RUNEWORDS = [
    # --- PATCH 3.0 / REIGN OF THE WARLOCK ---
    {"name": "BESESSENHEIT", "eng": "Obsession", "runes": ["Zod", "Ist", "Lem", "Lum", "Io", "Nef"], "lvl": 69,
     "sockets": 6, "type": "Stab", "patch": "3.0",
     "stats": "• Unzerstörbar\n• 24% Chance, Level 10 Schwächen bei Treffer zu zaubern\n• +4 zu allen Fertigkeiten\n• +65% Schnellere Zauberrate\n• +60% Schnellere Erholung nach Treffer\n• Rückstoßung\n• +10 zu Vitalität\n• +10 zu Energie\n• Erhöht maximales Leben um 15-25%\n• Mana regenerieren 15-30%\n• Alle Widerstandsarten +60-70\n• 75% Extragold von Monstern\n• 30% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "ZIRKEL", "eng": "Coven", "runes": ["Ist", "Ral", "Io"], "lvl": 63, "sockets": 3, "type": "Helm",
     "patch": "3.0", "stats": "• +1 zu allen Fertigkeiten\n• +20% Schnellere Zauberrate\n• +10 zu Vitalität\n• Feuer-Widerstand +30%\n• 31% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "RITUAL", "eng": "Ritual", "runes": ["Amn", "Shael", "Ohm"], "lvl": 57, "sockets": 3,
     "type": "Dolch", "patch": "3.0", "stats": "• 13% Chance auf Siegel: Tod bei Treffer\n• +304% Erhöhter Schaden\n• +40% Erhöhte Angriffsgeschwindigkeit\n• 7% Abgesaugtes Leben pro Treffer"},
    {"name": "WACHSAMKEIT", "eng": "Vigilance", "runes": ["Dol", "Gul"], "lvl": 53, "sockets": 2,
     "type": "Schild", "patch": "3.0", "stats": "• 5% Chance auf Feuerring bei Treffer\n• +10% Schneller Rennen/Gehen\n• +30% Schnellere Abblockrate\n• +7 Leben wiederherstellen\n• +5% zu Maximaler Gift-Widerstand"},
    {"name": "MACHT", "eng": "Power", "runes": ["Hel", "Shael", "Ral"], "lvl": 29, "sockets": 3,
     "type": "Rüstung", "patch": "3.0", "stats": "• +2 zu Hexenmeister-Fertigkeiten\n• 10% Chance auf Miasmakette bei Treffer\n• +20% Schnellere Erholung nach Treffer\n• Feuer-Widerstand +30%\n• Anforderungen -15%"},

    # --- PATCH 2.6 / 2.4 ---
    {"name": "MOSAIK", "eng": "Mosaic", "runes": ["Mal", "Gul", "Thul"], "lvl": 53, "sockets": 3,
     "type": "Klaue", "patch": "2.6",
     "stats": "• +2 zu Kampfkünsten (nur Assassine)\n• 50% Chance, bei Finisher-Moves Ladungen nicht zu verbrauchen\n• +20% Bonus zu Angriffswert\n• +8-15% zu Kälte/Blitz/Feuer-Schaden\n• Verhindert Monsterheilung\n• 20% Chance auf offene Wunden\n• Erhöht um 14 Kälteschaden\n• +5% zu Maximaler Gift-Widerstand"},
    {"name": "HETZE", "eng": "Hustle", "runes": ["Shael", "Ko", "Eld"], "lvl": 39, "sockets": 3,
     "type": "Waffe/Rüstung", "patch": "2.6",
     "stats": "• WAFFE:\n• 5% Chance, Level 1 Tempo auf Schlag zu zaubern\n• Level 1 Fanatismus-Aura\n• +30% Erhöhte Angriffsgeschwindigkeit\n• +130-150% Erhöhter Schaden\n• 75% Schaden an Untoten\n• +10 zu Geschicklichkeit\n\n• RÜSTUNG:\n• +65% Schneller Rennen/Gehen\n• +40% Erhöhte Angriffsgeschwindigkeit\n• +20% Schnellere Erholung nach Treffer\n• +6 zu Entrinnen\n• +10 zu Geschicklichkeit\n• 50% Ausdauer-Regeneration"},
    {"name": "METAMORPHOSE", "eng": "Metamorphosis", "runes": ["Io", "Cham", "Fal"], "lvl": 67, "sockets": 3,
     "type": "Helm", "patch": "2.6", "stats": "• Gewährt Mal des Wolfes/Bären\n• +5 zu Gestaltwandeln-Fertigkeiten\n• +25% Chance auf vernichtenden Schlag\n• +50-80% Erhöhte Verteidigung\n• +10 zu Vitalität\n• +10 zu Stärke\n• Einfrieren nicht möglich"},
    {"name": "FLACKERNDE FLAMME", "eng": "Flickering Flame", "runes": ["Nef", "Pul", "Vex"], "lvl": 55,
     "sockets": 3, "type": "Helm", "patch": "2.4", "stats": "• Level 4-8 Widerstand gegen Feuer Aura\n• +3 zu Feuer-Fertigkeiten\n• -10-15% zu Feuer-Widerstand des Gegners\n• +30% Verbesserte Verteidigung\n• +5% zu Maximaler Feuer-Widerstand\n• +50-75 zu Mana\n• Rückstoßung"},
    {"name": "HEILUNG", "eng": "Cure", "runes": ["Shael", "Io", "Tal"], "lvl": 35, "sockets": 3, "type": "Helm",
     "patch": "2.6", "stats": "• Level 1 Reinigung-Aura wenn ausgerüstet\n• +20% Schnellere Erholung nach Treffer\n• +75-100% Verbesserte Verteidigung\n• Erhöht maximales Leben um 5%\n• +10 zu Vitalität\n• Gift-Widerstand +40-60%\n• Giftstärke reduziert um 50%"},
    {"name": "NEBEL", "eng": "Mist", "runes": ["Cham", "Shael", "Gul", "Thul", "Ith"], "lvl": 67, "sockets": 5,
     "type": "Bogen", "patch": "2.4", "stats": "• Level 8-12 Konzentration Aura\n• +3 zu allen Fertigkeiten\n• 20% Erhöhte Angriffsgeschwindigkeit\n• 100% Stech-Angriff\n• +327% Erhöhter Schaden\n• Alle Widerstandsarten +40\n• Einfrieren nicht möglich\n• 20% Bonus zu Angriffswert"},
    {"name": "UNBEUGSAMER WILLE", "eng": "Unbending Will", "runes": ["Fal", "Io", "Ith", "Eld", "El", "Hel"],
     "lvl": 41, "sockets": 6, "type": "Schwert", "patch": "2.4", "stats": "• 18% Chance, Level 18 Hohn auf Schlag zu zaubern\n• +3 zu Kampf-Fertigkeiten (nur Barbar)\n• +20-30% Erhöhte Angriffsgeschwindigkeit\n• +330% Erhöhter Schaden\n• +75% Schaden an Untoten\n• +9 zu Maximalschaden\n• +10 zu Stärke / +10 zu Vitalität\n• Anforderungen -20%"},
    {"name": "WEISHEIT", "eng": "Wisdom", "runes": ["Pul", "Ith", "Eld"], "lvl": 45, "sockets": 3,
     "type": "Helm", "patch": "2.4", "stats": "• 33% Stech-Angriff\n• +20% Bonus zu Angriffswert\n• 5% Abgesaugtes Mana pro Treffer\n• +30% Verbesserte Verteidigung\n• +10 zu Energie\n• Einfrieren nicht möglich\n• +5 zu Mana nach jedem Volltreffer"},

    # --- KLASSIKER & HIGH-END ---
    {"name": "RÄTSEL", "eng": "Enigma", "runes": ["Jah", "Ith", "Ber"], "lvl": 65, "sockets": 3,
     "type": "Rüstung", "patch": "1.10",
     "stats": "• +2 zu allen Fertigkeiten\n• +45% Schneller Rennen/Gehen\n• +1 zu Teleportieren\n• +750-775 Verteidigung\n• + (0.75 pro Level) zu Stärke\n• Erhöht maximales Leben um 5%\n• Schaden reduziert um 8%\n• +14 Leben nach jedem Volltreffer\n• 15% erlittener Schaden geht auf Mana\n• + (1 pro Level)% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "GEIST", "eng": "Spirit", "runes": ["Tal", "Thul", "Ort", "Amn"], "lvl": 25, "sockets": 4,
     "type": "Schwert/Schild", "patch": "1.10", "stats": "• +2 zu allen Fertigkeiten\n• +25-35% Schnellere Zauberrate\n• +55% Schnellere Erholung nach Treffer\n• +250 zur Verteidigung gegen Geschosse\n• +22 zu Vitalität\n• +89-112 zu Mana\n• Magie-Absorption 3-8\n• WAFFE: +1-50 Blitzschaden, 7% Lebensabsaugung\n• SCHILD: Kälte/Blitz/Gift-Widerstand +35%"},
    {"name": "TRAUER", "eng": "Grief", "runes": ["Eth", "Tir", "Lo", "Mal", "Ral"], "lvl": 59, "sockets": 5,
     "type": "Waffe", "patch": "1.10", "stats": "• 35% Chance, Level 15 Giftgeifer auf Schlag zu zaubern\n• +30-40% Erhöhte Angriffsgeschwindigkeit\n• Schaden +340-400\n• Verteidigung des Ziels ignorieren\n• -25% Ziel-Verteidigung\n• + (1.875 pro Level)% Schaden an Dämonen\n• Fügt 5-30 Feuerschaden zu\n• -20-25% zu Gift-Widerstand des Gegners\n• 20% Todesschlag\n• Verhindert Monsterheilung\n• +2 zu Mana / +10-15 Leben nach jedem Volltreffer"},
    {"name": "UNENDLICHKEIT", "eng": "Infinity", "runes": ["Ber", "Mal", "Ber", "Ist"], "lvl": 63, "sockets": 4,
     "type": "Waffe", "patch": "1.10", "stats": "• 50% Chance, Level 20 Kettenblitz nach Tod zu zaubern\n• Level 12 Überzeugungs-Aura wenn ausgerüstet\n• +35% Schneller Rennen/Gehen\n• +255-325% Erhöhter Schaden\n• -45-55% zu Blitz-Widerstand des Gegners\n• 40% Chance auf vernichtenden Schlag\n• Verhindert Monsterheilung\n• + (0.5 pro Level) zu Vitalität\n• 30% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "RUF ZU DEN WAFFEN", "eng": "Call to Arms", "runes": ["Amn", "Ral", "Mal", "Ist", "Ohm"], "lvl": 57,
     "sockets": 5, "type": "Waffe", "patch": "1.10", "stats": "• +1 zu allen Fertigkeiten\n• +40% Erhöhte Angriffsgeschwindigkeit\n• +250-290% Erhöhter Schaden\n• +1-6 zu Kampfbefehle\n• +2-6 zu Kampfaufruf\n• +1-4 zu Schlachtruf\n• Leben wiederherstellen +12\n• 30% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "ODEM DER STERBENDEN", "eng": "BOTD", "runes": ["Vex", "Hel", "El", "Eld", "Zod", "Eth"],
     "lvl": 69, "sockets": 6, "type": "Waffe", "patch": "1.10",
     "stats": "• 50% Chance, Level 20 Giftnova nach Tod zu zaubern\n• Unzerstörbar\n• +60% Erhöhte Angriffsgeschwindigkeit\n• +350-400% Erhöhter Schaden\n• 12-15% Abgesaugtes Leben\n• 7% Abgesaugtes Mana\n• +30 zu allen Attributen\n• Verhindert Monsterheilung\n• -25% Ziel-Verteidigung"},
    {"name": "HERZ DER EICHE", "eng": "HOTO", "runes": ["Ko", "Vex", "Pul", "Thul"], "lvl": 55, "sockets": 4,
     "type": "Flegel/Stab", "patch": "1.10", "stats": "• +3 zu allen Fertigkeiten\n• +40% Schnellere Zauberrate\n• +75% Schaden an Dämonen\n• +10 zu Geschicklichkeit\n• Leben wiederherstellen +20\n• Erhöht maximales Mana um 15%\n• Alle Widerstandsarten +30-40\n• Level 4 Eichbaumweiser (25 Ladungen)"},
    {"name": "STÄRKE", "eng": "Fortitude", "runes": ["El", "Sol", "Dol", "Lo"], "lvl": 59, "sockets": 4,
     "type": "Rüstung/Waffe", "patch": "1.10", "stats": "• 20% Chance, Level 15 Zitterrüstung bei Treffer zu zaubern\n• +25% Schnellere Zauberrate\n• +300% Erhöhter Schaden\n• +200% Verbesserte Verteidigung\n• + (1-1.5 pro Level) zu Leben\n• Alle Widerstandsarten +25-30\n• 12% erlittener Schaden geht auf Mana\n• +5% zu Maximaler Blitz-Widerstand"},
    {"name": "PHÖNIX", "eng": "Phoenix", "runes": ["Vex", "Vex", "Lo", "Jah"], "lvl": 65, "sockets": 4,
     "type": "Waffe/Schild", "patch": "1.10", "stats": "• 100% Chance, Level 40 Feuersbrunst bei Level-Up zu zaubern\n• Level 10-15 Rücknahme-Aura wenn ausgerüstet\n• +350-400% Erhöhter Schaden\n• -28% zu Feuer-Widerstand des Gegners\n• +50 zu Leben\n• +5% zu Maximaler Blitz-Widerstand\n• +10% zu Maximaler Feuer-Widerstand"},
    {"name": "TRAUM", "eng": "Dream", "runes": ["Io", "Jah", "Pul"], "lvl": 65, "sockets": 3,
     "type": "Helm/Schild", "patch": "1.10", "stats": "• 10% Chance, Level 15 Verwirren bei Treffer zu zaubern\n• Level 15 Heiliger Schock-Aura wenn ausgerüstet\n• +20-30% Schnellere Erholung nach Treffer\n• +30% Verbesserte Verteidigung\n• +150-220 Verteidigung\n• +10 zu Vitalität\n• Erhöht maximales Leben um 5% (Helm) / +50 Leben (Schild)\n• Alle Widerstandsarten +5-20\n• 12-25% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "DRACHE", "eng": "Dragon", "runes": ["Sur", "Lo", "Sol"], "lvl": 61, "sockets": 3,
     "type": "Rüstung/Schild", "patch": "1.10", "stats": "• 20% Chance, Level 18 Giftgeifer bei Treffer zu zaubern\n• 12% Chance, Level 15 Hydra auf Schlag zu zaubern\n• Level 14 Heiliges Feuer-Aura wenn ausgerüstet\n• +360 Verteidigung\n• +230 zur Verteidigung gegen Geschosse\n• +3-5 zu allen Attributen\n• + (0.375 pro Level) zu Stärke\n• Erhöht maximales Mana um 5%"},
    {"name": "EXIL", "eng": "Exile", "runes": ["Vex", "Ohm", "Ist", "Dol"], "lvl": 57, "sockets": 4,
     "type": "Paladin-Schild", "patch": "1.10", "stats": "• 15% Chance, Level 5 Lebens-Spender auf Schlag zu zaubern\n• Level 13-16 Trotz-Aura wenn ausgerüstet\n• +2 zu offensiven Auren (nur Paladin)\n• +30% Schnellere Abblockrate\n• Ziel erstarren lassen\n• +220-260% Verbesserte Verteidigung\n• Leben wiederherstellen +7\n• +5% zu Maximaler Kälte/Feuer-Widerstand\n• Repariert Haltbarkeit (1 in 4 Sekunden)"},
    {"name": "STOLZ", "eng": "Pride", "runes": ["Cham", "Sur", "Io", "Lo"], "lvl": 67, "sockets": 4,
     "type": "Stangenwaffe", "patch": "1.10", "stats": "• 25% Chance, Level 17 Feuerwand bei Treffer zu zaubern\n• Level 16-20 Konzentration-Aura wenn ausgerüstet\n• +260-300% Bonus zu Angriffswert\n• +1-99% Schaden an Dämonen\n• Fügt 50-280 Blitzschaden zu\n• 20% Todesschlag\n• Treffer blendet Ziel\n• Ziel erstarren lassen\n• +10 zu Vitalität"},
    {"name": "GLAUBE", "eng": "Faith", "runes": ["Ohm", "Jah", "Lem", "Eld"], "lvl": 65, "sockets": 4,
     "type": "Bogen", "patch": "1.10", "stats": "• Level 12-15 Fanatismus-Aura wenn ausgerüstet\n• +1-2 zu allen Fertigkeiten\n• +330% Erhöhter Schaden\n• Verteidigung des Ziels ignorieren\n• 300% Bonus zu Angriffswert\n• +120 Feuerschaden\n• Alle Widerstandsarten +15\n• 10% Wiederbeleben\n• 75% Extragold von Monstern"},
    {"name": "DORNEN", "eng": "Bramble", "runes": ["Ral", "Ohm", "Sur", "Eth"], "lvl": 61, "sockets": 4,
     "type": "Rüstung", "patch": "1.10", "stats": "• Level 15-21 Dornen-Aura wenn ausgerüstet\n• +50% Schnellere Erholung nach Treffer\n• +25-50% zu Gift-Fertigkeit-Schaden\n• +300 Verteidigung\n• Erhöht maximales Mana um 5%\n• Mana regenerieren +15%\n• +5% zu Maximaler Kälte-Widerstand\n• Feuer-Widerstand +30%\n• Gift-Widerstand +100%\n• +13 Leben nach jedem Volltreffer"},
    {"name": "LETZTER WUNSCH", "eng": "Last Wish", "runes": ["Jah", "Mal", "Jah", "Sur", "Jah", "Ber"],
     "lvl": 65, "sockets": 6, "type": "Waffe", "patch": "1.10", "stats": "• 6% Chance, Level 11 Verblassen bei Treffer zu zaubern\n• 10% Chance, Level 18 Lebens-Spender auf Schlag zu zaubern\n• 20% Chance, Level 20 Combo-Blitz auf Angriff zu zaubern\n• Level 17 Macht-Aura wenn ausgerüstet\n• +330-375% Erhöhter Schaden\n• Verteidigung des Ziels ignorieren\n• 60-70% Chance auf vernichtenden Schlag\n• Treffer blendet Ziel\n• 0.5% Bessere Chance, magischen Gegenstand zu finden (pro Level)"},

    # --- STARTER & MID-RANGE ---
    {"name": "HEIMLICHKEIT", "eng": "Stealth", "runes": ["Tal", "Eth"], "lvl": 17, "sockets": 2,
     "type": "Rüstung", "patch": "1.09", "stats": "• +25% Schneller Rennen/Gehen\n• +25% Schnellere Zauberrate\n• +25% Schnellere Erholung nach Treffer\n• +6 zu Geschicklichkeit\n• +15 zu maximaler Ausdauer\n• Gift-Widerstand +30%\n• Mana regenerieren +15%\n• Magieschaden reduziert um 3"},
    {"name": "ÜBERLIEFERUNG", "eng": "Lore", "runes": ["Ort", "Sol"], "lvl": 27, "sockets": 2, "type": "Helm",
     "patch": "1.09", "stats": "• +1 zu allen Fertigkeiten\n• +10 zu Energie\n• +2 zu Mana nach jedem Volltreffer\n• Blitz-Widerstand +30%\n• Schaden reduziert um 7\n• +2 zu Lichtradius"},
    {"name": "REIM", "eng": "Rhyme", "runes": ["Shael", "Eth"], "lvl": 29, "sockets": 2, "type": "Schild",
     "patch": "1.09", "stats": "• +20% Erhöhte Blockchance\n• +40% Schnellere Abblockrate\n• Alle Widerstandsarten +25\n• Mana regenerieren +15%\n• Einfrieren nicht möglich\n• 50% Extragold von Monstern\n• 25% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "WEISS", "eng": "White", "runes": ["Dol", "Io"], "lvl": 35, "sockets": 2, "type": "Stab",
     "patch": "1.09", "stats": "• +3 zu Gift- und Knochen-Fertigkeiten\n• +20% Schnellere Zauberrate\n• +2 zu Knochenspeer\n• +4 zu Skelett-Beherrschung\n• +3 zu Knochenrüstung\n• Treffer veranlasst Monster zur Flucht (25%)\n• +10 zu Vitalität\n• +13 zu Mana\n• Magieschaden reduziert um 4"},
    {"name": "STAHL", "eng": "Steel", "runes": ["Tir", "El"], "lvl": 13, "sockets": 2, "type": "Waffe",
     "patch": "1.09", "stats": "• +20% Erhöhter Schaden\n• +3 zu Minimalschaden / +3 zu Maximalschaden\n• +50 zu Angriffswert\n• 50% Chance auf offene Wunden\n• 25% Erhöhte Angriffsgeschwindigkeit\n• +2 zu Mana nach jedem Volltreffer\n• +1 zu Lichtradius"},
    {"name": "BLATT", "eng": "Leaf", "runes": ["Tir", "Ral"], "lvl": 19, "sockets": 2, "type": "Stab",
     "patch": "1.09", "stats": "• +3 zu Feuer-Fertigkeiten\n• Fügt 5-30 Feuerschaden zu\n• +3 zu Inferno (Sorc)\n• +3 zu Wärme (Sorc)\n• +3 zu Feuerblitz (Sorc)\n• + (2 pro Level) Verteidigung\n• Kälte-Widerstand +33%\n• +2 zu Mana nach jedem Volltreffer"},
    {"name": "BOSHAFTIGKEIT", "eng": "Malice", "runes": ["Ith", "El", "Eth"], "lvl": 15, "sockets": 3,
     "type": "Waffe", "patch": "1.09", "stats": "• +33% Erhöhter Schaden\n• +9 zu Maximalschaden\n• 100% Chance auf offene Wunden\n• -25% Ziel-Verteidigung\n• -100 zur Verteidigung gegen Monster\n• Verhindert Monsterheilung\n• +50 zu Angriffswert\n• Leben absaugen -5"},
    {"name": "VERRAT", "eng": "Treachery", "runes": ["Shael", "Thul", "Lem"], "lvl": 43, "sockets": 3,
     "type": "Rüstung", "patch": "1.11", "stats": "• 5% Chance, Level 15 Verblassen bei Treffer zu zaubern\n• 25% Chance, Level 15 Giftgeifer auf Schlag zu zaubern\n• +2 zu Fertigkeiten der Assassine\n• +45% Erhöhte Angriffsgeschwindigkeit\n• +20% Schnellere Erholung nach Treffer\n• Kälte-Widerstand +30%\n• 50% Extragold von Monstern"},
    {"name": "GEHORSAM", "eng": "Obedience", "runes": ["Hel", "Ko", "Thul", "Eth", "Fal"], "lvl": 41,
     "sockets": 5, "type": "Stangenwaffe", "patch": "1.10", "stats": "• 30% Chance, Level 21 Verzaubern nach Tod zu zaubern\n• +370% Erhöhter Schaden\n• -25% Ziel-Verteidigung\n• +3 bis 14 Kälteschaden\n• -25% zu Feuer-Widerstand des Gegners\n• 40% Chance auf vernichtenden Schlag\n• +200-300 Verteidigung\n• +10 zu Stärke / +10 zu Geschicklichkeit\n• Alle Widerstandsarten +20-30\n• Anforderungen -20%"},
    {"name": "RAUCH", "eng": "Smoke", "runes": ["Nef", "Lum"], "lvl": 37, "sockets": 2, "type": "Rüstung",
     "patch": "1.09", "stats": "• +20% Schnellere Erholung nach Treffer\n• +75% Verbesserte Verteidigung\n• +280 zur Verteidigung gegen Geschosse\n• Alle Widerstandsarten +50\n• +10 zu Energie\n• Schwächt erlittenen Schaden um 1"},
    {"name": "ERLEUCHTUNG", "eng": "Enlightenment", "runes": ["Pul", "Ral", "Sol"], "lvl": 45, "sockets": 3,
     "type": "Rüstung", "patch": "1.11", "stats": "• 5% Chance, Level 15 Feuerball auf Schlag zu zaubern\n• +2 zu Fertigkeiten der Zauberin\n• +1 zu Wärme\n• +30% Verbesserte Verteidigung\n• Feuer-Widerstand +30%\n• Schaden reduziert um 7"},
    {"name": "FRIEDEN", "eng": "Peace", "runes": ["Shael", "Thul", "Amn"], "lvl": 29, "sockets": 3,
     "type": "Rüstung", "patch": "1.11", "stats": "• 4% Chance, Level 5 Langsame Geschosse bei Treffer zu zaubern\n• 2% Chance, Level 15 Walküre auf Schlag zu zaubern\n• +2 zu Fertigkeiten der Amazone\n• +20% Schnellere Erholung nach Treffer\n• +2 zu Kritischer Schlag\n• Kälte-Widerstand +30%\n• Angreifer erleidet Schaden von 14"},
    {"name": "MYTHOS", "eng": "Myth", "runes": ["Hel", "Amn", "Nef"], "lvl": 25, "sockets": 3,
     "type": "Rüstung", "patch": "1.11", "stats": "• 3% Chance, Level 1 Heulen bei Treffer zu zaubern\n• 10% Chance, Level 1 Hohn auf Schlag zu zaubern\n• +2 zu Fertigkeiten des Barbaren\n• +30 zur Verteidigung gegen Geschosse\n• Leben wiederherstellen +10\n• Angreifer erleidet Schaden von 14\n• Anforderungen -15%"},
    {"name": "KNOCHEN", "eng": "Bone", "runes": ["Sol", "Um", "Um"], "lvl": 47, "sockets": 3, "type": "Rüstung",
     "patch": "1.11", "stats": "• 15% Chance, Level 10 Knochenrüstung bei Treffer zu zaubern\n• +2 zu Fertigkeiten des Totenbeschwörers\n• +100-150 zu Mana\n• Alle Widerstandsarten +30\n• Schaden reduziert um 7"},
    {"name": "REGEN", "eng": "Rain", "runes": ["Ort", "Mal", "Ith"], "lvl": 49, "sockets": 3, "type": "Rüstung",
     "patch": "1.11", "stats": "• 5% Chance, Level 15 Zyklon-Rüstung bei Treffer zu zaubern\n• +2 zu Fertigkeiten des Druiden\n• +100-150 zu Mana\n• Blitz-Widerstand +30%\n• Magieschaden reduziert um 7\n• 15% erlittener Schaden geht auf Mana"},
    {"name": "PRINZIP", "eng": "Principle", "runes": ["Gul", "Sur", "Io"], "lvl": 53, "sockets": 3,
     "type": "Rüstung", "patch": "1.11", "stats": "• 100% Chance, Level 5 Heiliger Blitz auf Schlag zu zaubern\n• +2 zu Fertigkeiten des Paladins\n• +50% Schaden an Untoten\n• +100-150 zu Leben\n• +15% zu Maximaler Gift-Widerstand\n• +5% zu Maximaler Feuer-Widerstand"},
    {"name": "MONDSICHEL", "eng": "Crescent Moon", "runes": ["Shael", "Um", "Tir"], "lvl": 47, "sockets": 3,
     "type": "Axt/Schwert/Stange", "patch": "1.10", "stats": "• 10% Chance, Level 17 Kettenblitz auf Schlag zu zaubern\n• -35% zu Blitz-Widerstand des Gegners\n• +20% Erhöhte Angriffsgeschwindigkeit\n• +180-220% Erhöhter Schaden\n• Verteidigung des Ziels ignorieren\n• 25% Chance auf offene Wunden\n• +9-11 Magie-Absorption\n• +2 zu Mana nach jedem Volltreffer"},
    {"name": "HARMONIE", "eng": "Harmony", "runes": ["Tir", "Ith", "Sol", "Ko"], "lvl": 39, "sockets": 4,
     "type": "Bogen", "patch": "1.10", "stats": "• Level 10 Gedeihen-Aura wenn ausgerüstet\n• +200-275% Erhöhter Schaden\n• +9 zu Minimalschaden / +9 zu Maximalschaden\n• Fügt 55-160 Feuer/Blitz/Kälte-Schaden zu\n• +2-6 zu Walküre\n• +10 zu Geschicklichkeit\n• Mana regenerieren 20%\n• +2 zu Mana nach jedem Volltreffer\n• +2 zu Lichtradius"},
    {"name": "EID", "eng": "Oath", "runes": ["Shael", "Pul", "Mal", "Lum"], "lvl": 49, "sockets": 4,
     "type": "Waffe", "patch": "1.10", "stats": "• 30% Chance, Level 20 Knochengeist auf Schlag zu zaubern\n• Unzerstörbar\n• +50% Erhöhte Angriffsgeschwindigkeit\n• +210-340% Erhöhter Schaden\n• +75% Schaden an Dämonen / +100 AR gegen Dämonen\n• Verhindert Monsterheilung\n• +10 zu Energie\n• Magie-Absorption 10-15\n• Level 16 Herz des Wiesels (20 Ladungen)"},
    {"name": "TOD", "eng": "Death", "runes": ["Hel", "El", "Vex", "Ort", "Gul"], "lvl": 55, "sockets": 5,
     "type": "Waffe", "patch": "1.10", "stats": "• 100% Chance, Level 44 Kettenblitz nach Tod zu zaubern\n• 25% Chance, Level 18 Gletschernadel auf Angriff zu zaubern\n• Unzerstörbar\n• +300-385% Erhöhter Schaden\n• 20% Bonus zu Angriffswert\n• 50% Chance auf vernichtenden Schlag\n• + (0.5 pro Level)% Todesschlag\n• 7% Abgesaugtes Mana pro Treffer\n• +50 zu Angriffswert\n• +1 zu Lichtradius\n• Anforderungen -20%"},
    {"name": "EINSICHT", "eng": "Insight", "runes": ["Ral", "Tir", "Tal", "Sol"], "lvl": 27, "sockets": 4,
     "type": "Waffe", "patch": "1.10", "stats": "• Level 12-17 Meditations-Aura wenn ausgerüstet\n• +35% Schnellere Zauberrate\n• +200-260% Erhöhter Schaden\n• +9 zu Minimalschaden\n• 180-250% Bonus zu Angriffswert\n• +5-30 Feuerschaden\n• +75 Giftschaden über 5 Sekunden\n• +1-6 zu Kritischer Schlag\n• +5 zu allen Attributen\n• +2 zu Mana nach jedem Volltreffer\n• 23% Bessere Chance, magischen Gegenstand zu finden"},
    {"name": "KÖNIGSMORD", "eng": "Kingslayer", "runes": ["Mal", "Um", "Gul", "Fal"], "lvl": 53, "sockets": 4,
     "type": "Waffe", "patch": "1.10", "stats": "• +30% Erhöhte Angriffsgeschwindigkeit\n• +230-270% Erhöhter Schaden\n• -25% Ziel-Verteidigung\n• 20% Bonus zu Angriffswert\n• 33% Chance auf vernichtenden Schlag\n• 50% Chance auf offene Wunden\n• Verhindert Monsterheilung\n• +10 zu Stärke\n• 40% Extragold von Monstern"},
    {"name": "SCHNEIDE", "eng": "Edge", "runes": ["Tir", "Tal", "Amn"], "lvl": 25, "sockets": 3,
     "type": "Bogen", "patch": "1.10", "stats": "• Level 15 Dornen-Aura wenn ausgerüstet\n• +35% Erhöhte Angriffsgeschwindigkeit\n• +320-380% Schaden an Dämonen\n• +280% Schaden an Untoten\n• 7% Abgesaugtes Leben pro Treffer\n• Reduziert alle Händlerpreise um 15%\n• +5 bis 10 zu allen Attributen"},
    {"name": "WOHLSTAND", "eng": "Wealth", "runes": ["Lem", "Ko", "Tir"], "lvl": 43, "sockets": 3,
     "type": "Rüstung", "patch": "1.09", "stats": "• 300% Extragold von Monstern\n• 100% Bessere Chance, magischen Gegenstand zu finden\n• +10 zu Geschicklichkeit\n• +2 zu Mana nach jedem Volltreffer"},
    {"name": "ZEPHYR", "eng": "Zephyr", "runes": ["Ort", "Eth"], "lvl": 21, "sockets": 2, "type": "Bogen",
     "patch": "1.09", "stats": "• +25% Schneller Rennen/Gehen\n• +25% Erhöhte Angriffsgeschwindigkeit\n• +33% Erhöhter Schaden\n• -25% Ziel-Verteidigung\n• +66 zu Angriffswert\n• Fügt 1-50 Blitzschaden zu\n• +25 Verteidigung"},
    {"name": "ZUFLUCHT", "eng": "Sanctuary", "runes": ["Ko", "Ko", "Mal"], "lvl": 49, "sockets": 3,
     "type": "Schild", "patch": "1.10", "stats": "• +20% Schnellere Erholung nach Treffer\n• +20% Schnellere Abblockrate\n• 20% Erhöhte Blockchance\n• +130-160% Verbesserte Verteidigung\n• +250 zur Verteidigung gegen Geschosse\n• +20 zu Geschicklichkeit\n• Alle Widerstandsarten +50-70\n• Magieschaden reduziert um 7\n• Level 12 Langsame Geschosse (60 Ladungen)"},
    {"name": "LÖWENHERZ", "eng": "Lionheart", "runes": ["Hel", "Lum", "Fal"], "lvl": 41, "sockets": 3,
     "type": "Rüstung", "patch": "1.09", "stats": "• +20% Erhöhter Schaden\n• Anforderungen -15%\n• +25 zu Stärke\n• +15 zu Geschicklichkeit\n• +20 zu Vitalität\n• +10 zu Energie\n• +50 zu Leben\n• Alle Widerstandsarten +30"},
    {"name": "STILLE", "eng": "Silence", "runes": ["Dol", "Eld", "Hel", "Ist", "Tir", "Vex"], "lvl": 55,
     "sockets": 6, "type": "Waffe", "patch": "1.09", "stats": "• +2 zu allen Fertigkeiten\n• +20% Erhöhte Angriffsgeschwindigkeit\n• +200% Erhöhter Schaden\n• +75% Schaden an Untoten / +50 AR gegen Untote\n• 11% Abgesaugtes Mana pro Treffer\n• Treffer veranlasst Monster zur Flucht (25%)\n• Alle Widerstandsarten +75\n• +2 zu Mana nach jedem Volltreffer\n• 30% Bessere Chance, magischen Gegenstand zu finden\n• Anforderungen -20%"},
    {"name": "BOGEN_MELODIE", "eng": "Melody", "runes": ["Shael", "Ko", "Nef"], "lvl": 39, "sockets": 3,
     "type": "Bogen", "patch": "1.09", "stats": "• +3 zu Bogen- und Armbrust-Fertigkeiten (nur Amazone)\n• +20% Erhöhte Angriffsgeschwindigkeit\n• +50% Erhöhter Schaden\n• +300% Schaden an Untoten\n• +3 zu Ausweichen / Kritischer Schlag / Durchschlagen (Amazone)\n• Rückstoßung\n• +10 zu Geschicklichkeit"},
    {"name": "ERINNERUNG", "eng": "Memory", "runes": ["Lum", "Io", "Sol", "Eth"], "lvl": 37, "sockets": 4,
     "type": "Stab", "patch": "1.09", "stats": "• +3 zu Fertigkeiten der Zauberin\n• 33% Schnellere Zauberrate\n• Erhöht maximales Mana um 20%\n• +3 zu Energieschild (nur Zauberin)\n• +2 zu Statikfeld (nur Zauberin)\n• +10 zu Vitalität\n• +10 zu Energie\n• Magieschaden reduziert um 7\n• -25% Ziel-Verteidigung"},
    {"name": "KÖNIGLICHE GNADE", "eng": "King's Grace", "runes": ["Amn", "Ral", "Thul"], "lvl": 25,
     "sockets": 3, "type": "Schwert", "patch": "1.09", "stats": "• +100% Erhöhter Schaden\n• +100% Schaden an Dämonen\n• +50% Schaden an Untoten\n• Fügt 5-30 Feuerschaden zu\n• Fügt 3-14 Kälteschaden zu\n• 7% Abgesaugtes Leben pro Treffer\n• +150 zu Angriffswert"},
    {"name": "LEIDENSCHAFT", "eng": "Passion", "runes": ["Dol", "Ort", "Eld", "Lem"], "lvl": 43, "sockets": 4,
     "type": "Waffe", "patch": "1.10", "stats": "• +25% Erhöhte Angriffsgeschwindigkeit\n• +160-210% Erhöhter Schaden\n• +50-80% Bonus zu Angriffswert\n• +75% Schaden an Untoten / +50 AR gegen Untote\n• Fügt 1-50 Blitzschaden zu\n• +1 zu Eifer\n• +1 zu Amok\n• Treffer blendet Ziel (10)\n• Treffer veranlasst Monster zur Flucht (25%)\n• 75% Extragold von Monstern"},
    {"name": "NADIR", "eng": "Nadir", "runes": ["Nef", "Tir"], "lvl": 13, "sockets": 2, "type": "Helm",
     "patch": "1.09", "stats": "• +50% Verbesserte Verteidigung\n• +10 Verteidigung\n• +30 zur Verteidigung gegen Geschosse\n• +5 zu Stärke\n• +2 zu Mana nach jedem Volltreffer\n• -33% Extragold von Monstern\n• -3 zu Lichtradius\n• Level 13 Schattenmantel (9 Ladungen)"},
    {"name": "PRASSSELN", "eng": "Pattern", "runes": ["Tal", "Ort", "Thul"], "lvl": 23, "sockets": 3,
     "type": "Klaue", "patch": "2.4", "stats": "• +30% Schnelleres Blocken\n• +40-80% Erhöhter Schaden\n• +10% Bonus zu Angriffswert\n• Fügt 17-62 Feuer/Blitz/Kälte-Schaden zu\n• +15 zu allen Attributen\n• Alle Widerstandsarten +15\n• +2 zu Mana nach jedem Volltreffer"},
    {"name": "PEST", "eng": "Plague", "runes": ["Cham", "Shael", "Um"], "lvl": 67, "sockets": 3,
     "type": "Waffe", "patch": "2.4", "stats": "• 20% Chance, Level 12 Widerstandsschwund bei Treffer zu zaubern\n• 25% Chance, Level 15 Giftnova auf Schlag zu zaubern\n• Level 13-17 Reinigung-Aura wenn ausgerüstet\n• +1-2 zu allen Fertigkeiten\n• +20% Erhöhte Angriffsgeschwindigkeit\n• -23% zu Gift-Widerstand des Gegners\n• 0.3% (pro Level) Todesschlag\n• 25% Chance auf offene Wunden\n• Ziel erstarren lassen"},
    {"name": "BRAND", "eng": "Brand", "runes": ["Jah", "Lo", "Mal", "Gul"], "lvl": 65, "sockets": 4,
     "type": "Bogen", "patch": "1.10", "stats": "• 35% Chance, Level 14 Verstärkter Schaden bei Treffer zu zaubern\n• 100% Chance, Level 18 Knochenspeer auf Schlag zu zaubern\n• Feuert explosive Pfeile oder Bolzen (Level 15)\n• +260-340% Erhöhter Schaden\n• Verteidigung des Ziels ignorieren\n• 20% Todesschlag\n• +280-330% Schaden an Dämonen\n• Verhindert Monsterheilung\n• Rückstoßung"},
    {"name": "EIS", "eng": "Ice", "runes": ["Amn", "Shael", "Jah", "Lo"], "lvl": 65, "sockets": 4,
     "type": "Bogen", "patch": "1.10", "stats": "• 100% Chance, Level 40 Blizzard bei Level-Up zu zaubern\n• 25% Chance, Level 22 Frostnova auf Schlag zu zaubern\n• Level 18 Heiliger Frost-Aura wenn ausgerüstet\n• +20% Erhöhte Angriffsgeschwindigkeit\n• +140-210% Erhöhter Schaden\n• Verteidigung des Ziels ignorieren\n• +25-30% zu Kälte-Fertigkeit-Schaden\n• -20% zu Kälte-Widerstand des Gegners\n• 7% Abgesaugtes Leben\n• 20% Todesschlag"},
    {"name": "ZERSTÖRUNG", "eng": "Destruction", "runes": ["Vex", "Lo", "Ber", "Jah", "Ko"], "lvl": 65,
     "sockets": 5, "type": "Waffe", "patch": "1.10", "stats": "• 23% Chance, Level 12 Vulkan auf Schlag zu zaubern\n• 5% Chance, Level 23 Felsenfeuer auf Schlag zu zaubern\n• 100% Chance, Level 45 Meteor nach Tod zu zaubern\n• 15% Chance, Level 22 Nova auf Angriff zu zaubern\n• +350% Erhöhter Schaden\n• Verteidigung des Ziels ignorieren\n• 20% Chance auf vernichtenden Schlag\n• 20% Todesschlag\n• +10 zu Geschicklichkeit"},
    {"name": "UNENDLICH", "eng": "Boundless", "runes": ["Zod", "Cham", "Jah", "Ber"], "lvl": 69, "sockets": 4,
     "type": "Schild", "patch": "3.0", "stats": "• Unzerstörbar\n• +3 zu allen Fertigkeiten\n• Alle Widerstandsarten +50\n• Schaden reduziert um 15%\n• Einfrieren nicht möglich\n• +50 zu Leben\n• 15% erlittener Schaden geht auf Mana"},
    {"name": "EWIGKEIT", "eng": "Eternity", "runes": ["Amn", "Ber", "Ist", "Sol", "Sur"], "lvl": 63,
     "sockets": 5, "type": "Waffe", "patch": "1.10", "stats": "• Unzerstörbar\n• +260-310% Erhöhter Schaden\n• +9 zu Minimalschaden\n• 7% Abgesaugtes Leben pro Treffer\n• 20% Chance auf vernichtenden Schlag\n• Treffer blendet Ziel\n• Verlangsamt Ziel um 33%\n• Mana regenerieren 16%\n• Kann nicht eingefroren werden\n• 30% Bessere Chance, magischen Gegenstand zu finden\n• Level 8 Wiederbeleben (88 Ladungen)"}
]